# Generated by Django 6.0 on 2025-12-30 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_domain', models.CharField(db_index=True, max_length=255)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_member_id', models.CharField(blank=True, max_length=255, null=True)),
                ('terminal_id', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Terminal Links',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=255)),
                ('amount', models.IntegerField(help_text='Amount in cents')),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='started', max_length=20)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('receipt', models.TextField(blank=True, null=True)),
                ('shop_domain', models.CharField(max_length=255)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_member_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.terminallinks')),
            ],
        ),
    ]
