# Generated by Django 6.0 on 2026-01-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminallinks',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
